version: '3'

services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/opt/client
    ports:
      - 3000:3000

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/opt/server
    ports:
      - 8080:8080

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx:/usr/share/nginx/html
    ports:
      - 80:80
    depends_on:
      - client
      - server
