version: '3'

services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - db    

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - client
      - server

  # /* dsn: "postgresql://db_user:db_pass@hackz-megamouse-db-1:5432/db" */
  # db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: db_user
  #     POSTGRES_PASSWORD: db_pass
  #     POSTGRES_DB: db
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  
# volumes:
#   db_data: