version: '3'

services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/opt/client
    ports:
      - 8080:8080

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/opt/server
    ports:
      - 8081:8081