version: '3'

services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8081:8081

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - client
      - server
